name: Fetch Custom DuckDB
on:
  workflow_dispatch:
jobs:
  fetch-darwin-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch and Build DuckDB
        run: |
          make build.custom.duckdb DIRECTORY=https://github.com/taniabogatsch/duckdb.git BRANCH=logging