name: Fetch Custom DuckDB
on:
  workflow_dispatch:
jobs:
  fetch-darwin-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch and Build DuckDB
        run: |
          make fetch.custom.duckdb DIRECTORY=https://github.com/taniabogatsch/duckdb.git BRANCH=logging
          make split.artefacts DIRECTORY=custom-duckdb-linux-amd64 FILETYPE=o
          shell: bash
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push custom duckdb libs