name: Fetch Custom DuckDB
on:
  workflow_dispatch:
jobs:
  custom-linux-build:
    name: Custom Linux AMD64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build
        shell: bash
        run: |
          make fetch.custom.duckdb DIRECTORY=https://github.com/taniabogatsch/duckdb.git BRANCH=logging
          ls
          cd custom-duckdb-linux-amd64/duckdb
          export PWD=`pwd`
          docker run                                                             \
          -v$PWD:$PWD                                                            \
          -e CMAKE_BUILD_PARALLEL_LEVEL=2                                        \
          -e OVERRIDE_GIT_DESCRIBE=$OVERRIDE_GIT_DESCRIBE                        \
          -e EXTENSION_CONFIGS="$PWD/.github/config/bundled_extensions.cmake"    \
          -e BUILD_JEMALLOC=0                                                    \
          -e ENABLE_EXTENSION_AUTOLOADING=1                                      \
          -e ENABLE_EXTENSION_AUTOINSTALL=1                                      \
          -e BUILD_BENCHMARK=1                                                   \
          -e FORCE_WARN_UNUSED=1                                                 \
          quay.io/pypa/manylinux2014_x86_64                                      \
          bash -c "yum install -y perl-IPC-Cmd && git config --global --add safe.directory $PWD && make -C $PWD"

      - name: Extract Libs
        shell: bash
        run: |
          make extract.custom.libs

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push custom duckdb libs
